### ISSUE TITLE
I didn't know how else to do this

### ISSUE THREAD

**Issue by frontierpsycho** [spamguy/diplomacy#12]
Hey. This is just a shot in the dark, but I saw you starred my diplomacy project ([frontierpsycho/diplicitous](https://github.com/frontierpsychi/diplicitous)), and that you're working on an angularjs diplomacy interface. I'm going to make you an offer you can absolutely refuse. Wanna perhaps work together? :-)

**Comment by spamguy** [comment]
Greetings! Yeah, curse GitHub's lack of user messaging.

dipl.io is relatively new: I only [publicly announced it on Reddit a couple weeks ago](http://www.reddit.com/r/boardgames/comments/2xjiid/introducing_diplio_open_source_diplomacy_with_all/). I actually encountered diplicitous whilst researching judge adjudication. I stumbled upon [ruby-adjudicator](https://github.com/ruby-diplomacy/ruby-adjudicator) and was hoping to adapt that (with proper attribution! :) into a NodeJS module. I had been looking at [godip](https://github.com/zond/godip), but not speaking Go has made interpreting it tedious.

Anyway, I would love a collaboration! Technology-wise, it appears we're mostly on the same page already. Drop me an email (myusername@myusername.org, myusername being, er, my user name here) and we can discuss further.
