### ISSUE TITLE
Set Password Page Broken.

### ISSUE THREAD

**Issue by Schemetrical** [spamguy/diplomacy#22]
"Thanks for taking the time to verify your email address. Now, choose a password, and you're all set!"

The continue button is broken. OS X 10.11, Safari 9.1 Chrome 48.0

**Comment by spamguy** [comment]
Thanks for the report. It means a lot!

In addition I've deleted your previous account to prevent getting into a bad state. Kindly reregister and you should be good to go (again).

**Comment by Schemetrical** [comment]
Cool!
